apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-project
  template:
    metadata:
      labels:
        app: kube-project
    spec:
      containers:
      - name: kube-project-container
        image: prashanthallamvarma/kubernetes_project
        ports:
        - containerPort: 80
