apiVersion: v1
kind: Service
metadata:
  name: my-python-service
spec:
  selector:
    app: my-python-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 31200
  type: LoadBalancer
